--[[ ==========================================================================
	JCTDT - Vanilla Foods Expanded Compatibility
	Rewrites JCTDT's two can-opening recipes so their input lists and item
	mappers also cover the Vanilla Foods Expanded mod's canned foods.

	Technique borrowed from the Vanilla Foods Expanded mod itself (media/lua/shared/
	vfx_modifiedrecipes.lua): fetch the loaded recipe, clear its inputs/outputs,
	and re-Load it from an inline script string. This edits recipes on the fly
	and cleanly reverts if either mod is removed. This submod requires BOTH
	JustCraftTheDamnThing and VanillaFoodsExpanded (declared in mod.info), so the VFX.* item ids
	below always exist when this runs -> no "item not found" crash.
============================================================================ ]]

local function EditJCTDTRecipes()
	local recipeList = {
		["JCTDT_OpenCanScrewdriver"] = {
			inputs = [[
			item 1 tags[Screwdriver] mode:keep flags[MayDegradeLight], item 1 [Base.TinnedBeans;Base.CannedBolognese;Base.CannedCarrots2;Base.CannedChili;Base.CannedCorn;Base.CannedMilk;Base.CannedFruitBeverage;Base.CannedFruitCocktail;Base.CannedMushroomSoup;Base.CannedPeaches;Base.CannedPeas;Base.CannedPineapple;Base.CannedPotato2;Base.TinnedSoup;Base.CannedTomato2;Base.TunaTin;Base.Dogfood;Base.CannedCornedBeef;Base.CannedSardines;VFX.CannedAnchovies;VFX.CannedApplePieFilling;VFX.CannedAppleSlices;VFX.CannedApricots;VFX.CannedBeefMushroomStew;VFX.CannedBeefRavioli;VFX.CannedBlackBeans;VFX.CannedBlackberryPieFilling;VFX.CannedBlueberryPieFilling;VFX.CannedBroccoliCheddarSoup;VFX.CannedCatFood;VFX.CannedCherryPieFilling;VFX.CannedChicken;VFX.CannedChickenNoodleSoup;VFX.CannedChickpeas;VFX.CannedChiliBeanStew;VFX.CannedClamChowder;VFX.CannedCoconutCream;VFX.CannedCoconutMilk;VFX.CannedCreamCorn;VFX.CannedEdamameBeans;VFX.CannedFrenchOnionSoup;VFX.CannedGreenBeans;VFX.CannedHam;VFX.CannedIrishStew;VFX.CannedKidneyBeans;VFX.CannedLaksaNoodleSoup;VFX.CannedLemonCreamPieFilling;VFX.CannedLentilSoup;VFX.CannedLentils;VFX.CannedLychees;VFX.CannedMangoSlices;VFX.CannedMeatloaf;VFX.CannedMinestroneSoup;VFX.CannedMixedBerryPieFilling;VFX.CannedMixedVegetableMedley;VFX.CannedMushroomRavioli;VFX.CannedPassionfruit;VFX.CannedPeaHamSoup;VFX.CannedPeachPieFilling;VFX.CannedPearSlices;VFX.CannedPepperSteakStew;VFX.CannedPotatoLeekSoup;VFX.CannedPumpkinPuree;VFX.CannedPumpkinSoup;VFX.CannedRaspberryPieFilling;VFX.CannedRedBeansAndRice;VFX.CannedSalmon;VFX.CannedSavoryMince;VFX.CannedSlicedMushroom;VFX.CannedSloppyJoe;VFX.CannedSpaghetti;VFX.CannedSpaghettiAndMeatballs;VFX.CannedSpinach;VFX.CannedSpinachRavioli;VFX.CannedSteakOnionStew;VFX.CannedStrawberryPieFilling;VFX.CannedThreeBeanMix;VFX.CannedTomatoSoup;VFX.CannedVegetableStew;VFX.CannedVegetarianChili;VFX.CannedWhiteBeans] mappers[JCTDTcanSorts] flags[Prop2;DontPutBack],
			]],
			outputs = [[
			item 1 mapper:JCTDTcanSorts,
			]],
			mapper = [[itemMapper JCTDTcanSorts {
                Base.OpenBeans = Base.TinnedBeans,
                Base.CannedBologneseOpen = Base.CannedBolognese,
                Base.CannedCarrotsOpen = Base.CannedCarrots2,
                Base.CannedChiliOpen = Base.CannedChili,
                Base.CannedCornOpen = Base.CannedCorn,
                Base.CannedMilkOpen = Base.CannedMilk,
                Base.CannedFruitBeverageOpen = Base.CannedFruitBeverage,
                Base.CannedFruitCocktailOpen = Base.CannedFruitCocktail,
                Base.CannedMushroomSoupOpen = Base.CannedMushroomSoup,
                Base.CannedPeachesOpen = Base.CannedPeaches,
                Base.CannedPeasOpen = Base.CannedPeas,
                Base.CannedPineappleOpen = Base.CannedPineapple,
                Base.CannedPotatoOpen = Base.CannedPotato2,
                Base.TinnedSoupOpen = Base.TinnedSoup,
                Base.CannedTomatoOpen = Base.CannedTomato2,
                Base.TunaTinOpen = Base.TunaTin,
                Base.DogfoodOpen = Base.Dogfood,
                Base.CannedCornedBeefOpen = Base.CannedCornedBeef,
                Base.CannedSardinesOpen = Base.CannedSardines,
                VFX.CannedAnchoviesOpen = VFX.CannedAnchovies,
                VFX.CannedApplePieFillingOpen = VFX.CannedApplePieFilling,
                VFX.CannedAppleSlicesOpen = VFX.CannedAppleSlices,
                VFX.CannedApricotsOpen = VFX.CannedApricots,
                VFX.CannedBeefMushroomStewOpen = VFX.CannedBeefMushroomStew,
                VFX.CannedBeefRavioliOpen = VFX.CannedBeefRavioli,
                VFX.CannedBlackBeansOpen = VFX.CannedBlackBeans,
                VFX.CannedBlackberryPieFillingOpen = VFX.CannedBlackberryPieFilling,
                VFX.CannedBlueberryPieFillingOpen = VFX.CannedBlueberryPieFilling,
                VFX.CannedBroccoliCheddarSoupOpen = VFX.CannedBroccoliCheddarSoup,
                VFX.CannedCatFoodOpen = VFX.CannedCatFood,
                VFX.CannedCherryPieFillingOpen = VFX.CannedCherryPieFilling,
                VFX.CannedChickenOpen = VFX.CannedChicken,
                VFX.CannedChickenNoodleSoupOpen = VFX.CannedChickenNoodleSoup,
                VFX.CannedChickpeasOpen = VFX.CannedChickpeas,
                VFX.CannedChiliBeanStewOpen = VFX.CannedChiliBeanStew,
                VFX.CannedClamChowderOpen = VFX.CannedClamChowder,
                VFX.CannedCoconutCreamOpen = VFX.CannedCoconutCream,
                VFX.CannedCoconutMilkOpen = VFX.CannedCoconutMilk,
                VFX.CannedCreamCornOpen = VFX.CannedCreamCorn,
                VFX.CannedEdamameBeansOpen = VFX.CannedEdamameBeans,
                VFX.CannedFrenchOnionSoupOpen = VFX.CannedFrenchOnionSoup,
                VFX.CannedGreenBeansOpen = VFX.CannedGreenBeans,
                VFX.CannedHamOpen = VFX.CannedHam,
                VFX.CannedIrishStewOpen = VFX.CannedIrishStew,
                VFX.CannedKidneyBeansOpen = VFX.CannedKidneyBeans,
                VFX.CannedLaksaNoodleSoupOpen = VFX.CannedLaksaNoodleSoup,
                VFX.CannedLemonCreamPieFillingOpen = VFX.CannedLemonCreamPieFilling,
                VFX.CannedLentilSoupOpen = VFX.CannedLentilSoup,
                VFX.CannedLentilsOpen = VFX.CannedLentils,
                VFX.CannedLycheesOpen = VFX.CannedLychees,
                VFX.CannedMangoSlicesOpen = VFX.CannedMangoSlices,
                VFX.CannedMeatloafOpen = VFX.CannedMeatloaf,
                VFX.CannedMinestroneSoupOpen = VFX.CannedMinestroneSoup,
                VFX.CannedMixedBerryPieFillingOpen = VFX.CannedMixedBerryPieFilling,
                VFX.CannedMixedVegetableMedleyOpen = VFX.CannedMixedVegetableMedley,
                VFX.CannedMushroomRavioliOpen = VFX.CannedMushroomRavioli,
                VFX.CannedPassionfruitOpen = VFX.CannedPassionfruit,
                VFX.CannedPeaHamSoupOpen = VFX.CannedPeaHamSoup,
                VFX.CannedPeachPieFillingOpen = VFX.CannedPeachPieFilling,
                VFX.CannedPearSlicesOpen = VFX.CannedPearSlices,
                VFX.CannedPepperSteakStewOpen = VFX.CannedPepperSteakStew,
                VFX.CannedPotatoLeekSoupOpen = VFX.CannedPotatoLeekSoup,
                VFX.CannedPumpkinPureeOpen = VFX.CannedPumpkinPuree,
                VFX.CannedPumpkinSoupOpen = VFX.CannedPumpkinSoup,
                VFX.CannedRaspberryPieFillingOpen = VFX.CannedRaspberryPieFilling,
                VFX.CannedRedBeansAndRiceOpen = VFX.CannedRedBeansAndRice,
                VFX.CannedSalmonOpen = VFX.CannedSalmon,
                VFX.CannedSavoryMinceOpen = VFX.CannedSavoryMince,
                VFX.CannedSlicedMushroomOpen = VFX.CannedSlicedMushroom,
                VFX.CannedSloppyJoeOpen = VFX.CannedSloppyJoe,
                VFX.CannedSpaghettiOpen = VFX.CannedSpaghetti,
                VFX.CannedSpaghettiAndMeatballsOpen = VFX.CannedSpaghettiAndMeatballs,
                VFX.CannedSpinachOpen = VFX.CannedSpinach,
                VFX.CannedSpinachRavioliOpen = VFX.CannedSpinachRavioli,
                VFX.CannedSteakOnionStewOpen = VFX.CannedSteakOnionStew,
                VFX.CannedStrawberryPieFillingOpen = VFX.CannedStrawberryPieFilling,
                VFX.CannedThreeBeanMixOpen = VFX.CannedThreeBeanMix,
                VFX.CannedTomatoSoupOpen = VFX.CannedTomatoSoup,
                VFX.CannedVegetableStewOpen = VFX.CannedVegetableStew,
                VFX.CannedVegetarianChiliOpen = VFX.CannedVegetarianChili,
                VFX.CannedWhiteBeansOpen = VFX.CannedWhiteBeans,
            }]],
		},
		["JCTDT_OpenCanScissors"] = {
			inputs = [[
			item 1 tags[Scissors] mode:keep flags[MayDegradeLight], item 1 [Base.TinnedBeans;Base.CannedBolognese;Base.CannedCarrots2;Base.CannedChili;Base.CannedCorn;Base.CannedMilk;Base.CannedFruitBeverage;Base.CannedFruitCocktail;Base.CannedMushroomSoup;Base.CannedPeaches;Base.CannedPeas;Base.CannedPineapple;Base.CannedPotato2;Base.TinnedSoup;Base.CannedTomato2;Base.TunaTin;Base.Dogfood;Base.CannedCornedBeef;Base.CannedSardines;VFX.CannedAnchovies;VFX.CannedApplePieFilling;VFX.CannedAppleSlices;VFX.CannedApricots;VFX.CannedBeefMushroomStew;VFX.CannedBeefRavioli;VFX.CannedBlackBeans;VFX.CannedBlackberryPieFilling;VFX.CannedBlueberryPieFilling;VFX.CannedBroccoliCheddarSoup;VFX.CannedCatFood;VFX.CannedCherryPieFilling;VFX.CannedChicken;VFX.CannedChickenNoodleSoup;VFX.CannedChickpeas;VFX.CannedChiliBeanStew;VFX.CannedClamChowder;VFX.CannedCoconutCream;VFX.CannedCoconutMilk;VFX.CannedCreamCorn;VFX.CannedEdamameBeans;VFX.CannedFrenchOnionSoup;VFX.CannedGreenBeans;VFX.CannedHam;VFX.CannedIrishStew;VFX.CannedKidneyBeans;VFX.CannedLaksaNoodleSoup;VFX.CannedLemonCreamPieFilling;VFX.CannedLentilSoup;VFX.CannedLentils;VFX.CannedLychees;VFX.CannedMangoSlices;VFX.CannedMeatloaf;VFX.CannedMinestroneSoup;VFX.CannedMixedBerryPieFilling;VFX.CannedMixedVegetableMedley;VFX.CannedMushroomRavioli;VFX.CannedPassionfruit;VFX.CannedPeaHamSoup;VFX.CannedPeachPieFilling;VFX.CannedPearSlices;VFX.CannedPepperSteakStew;VFX.CannedPotatoLeekSoup;VFX.CannedPumpkinPuree;VFX.CannedPumpkinSoup;VFX.CannedRaspberryPieFilling;VFX.CannedRedBeansAndRice;VFX.CannedSalmon;VFX.CannedSavoryMince;VFX.CannedSlicedMushroom;VFX.CannedSloppyJoe;VFX.CannedSpaghetti;VFX.CannedSpaghettiAndMeatballs;VFX.CannedSpinach;VFX.CannedSpinachRavioli;VFX.CannedSteakOnionStew;VFX.CannedStrawberryPieFilling;VFX.CannedThreeBeanMix;VFX.CannedTomatoSoup;VFX.CannedVegetableStew;VFX.CannedVegetarianChili;VFX.CannedWhiteBeans] mappers[JCTDTcanSorts2] flags[Prop2;DontPutBack],
			]],
			outputs = [[
			item 1 mapper:JCTDTcanSorts2,
			]],
			mapper = [[itemMapper JCTDTcanSorts2 {
                Base.OpenBeans = Base.TinnedBeans,
                Base.CannedBologneseOpen = Base.CannedBolognese,
                Base.CannedCarrotsOpen = Base.CannedCarrots2,
                Base.CannedChiliOpen = Base.CannedChili,
                Base.CannedCornOpen = Base.CannedCorn,
                Base.CannedMilkOpen = Base.CannedMilk,
                Base.CannedFruitBeverageOpen = Base.CannedFruitBeverage,
                Base.CannedFruitCocktailOpen = Base.CannedFruitCocktail,
                Base.CannedMushroomSoupOpen = Base.CannedMushroomSoup,
                Base.CannedPeachesOpen = Base.CannedPeaches,
                Base.CannedPeasOpen = Base.CannedPeas,
                Base.CannedPineappleOpen = Base.CannedPineapple,
                Base.CannedPotatoOpen = Base.CannedPotato2,
                Base.TinnedSoupOpen = Base.TinnedSoup,
                Base.CannedTomatoOpen = Base.CannedTomato2,
                Base.TunaTinOpen = Base.TunaTin,
                Base.DogfoodOpen = Base.Dogfood,
                Base.CannedCornedBeefOpen = Base.CannedCornedBeef,
                Base.CannedSardinesOpen = Base.CannedSardines,
                VFX.CannedAnchoviesOpen = VFX.CannedAnchovies,
                VFX.CannedApplePieFillingOpen = VFX.CannedApplePieFilling,
                VFX.CannedAppleSlicesOpen = VFX.CannedAppleSlices,
                VFX.CannedApricotsOpen = VFX.CannedApricots,
                VFX.CannedBeefMushroomStewOpen = VFX.CannedBeefMushroomStew,
                VFX.CannedBeefRavioliOpen = VFX.CannedBeefRavioli,
                VFX.CannedBlackBeansOpen = VFX.CannedBlackBeans,
                VFX.CannedBlackberryPieFillingOpen = VFX.CannedBlackberryPieFilling,
                VFX.CannedBlueberryPieFillingOpen = VFX.CannedBlueberryPieFilling,
                VFX.CannedBroccoliCheddarSoupOpen = VFX.CannedBroccoliCheddarSoup,
                VFX.CannedCatFoodOpen = VFX.CannedCatFood,
                VFX.CannedCherryPieFillingOpen = VFX.CannedCherryPieFilling,
                VFX.CannedChickenOpen = VFX.CannedChicken,
                VFX.CannedChickenNoodleSoupOpen = VFX.CannedChickenNoodleSoup,
                VFX.CannedChickpeasOpen = VFX.CannedChickpeas,
                VFX.CannedChiliBeanStewOpen = VFX.CannedChiliBeanStew,
                VFX.CannedClamChowderOpen = VFX.CannedClamChowder,
                VFX.CannedCoconutCreamOpen = VFX.CannedCoconutCream,
                VFX.CannedCoconutMilkOpen = VFX.CannedCoconutMilk,
                VFX.CannedCreamCornOpen = VFX.CannedCreamCorn,
                VFX.CannedEdamameBeansOpen = VFX.CannedEdamameBeans,
                VFX.CannedFrenchOnionSoupOpen = VFX.CannedFrenchOnionSoup,
                VFX.CannedGreenBeansOpen = VFX.CannedGreenBeans,
                VFX.CannedHamOpen = VFX.CannedHam,
                VFX.CannedIrishStewOpen = VFX.CannedIrishStew,
                VFX.CannedKidneyBeansOpen = VFX.CannedKidneyBeans,
                VFX.CannedLaksaNoodleSoupOpen = VFX.CannedLaksaNoodleSoup,
                VFX.CannedLemonCreamPieFillingOpen = VFX.CannedLemonCreamPieFilling,
                VFX.CannedLentilSoupOpen = VFX.CannedLentilSoup,
                VFX.CannedLentilsOpen = VFX.CannedLentils,
                VFX.CannedLycheesOpen = VFX.CannedLychees,
                VFX.CannedMangoSlicesOpen = VFX.CannedMangoSlices,
                VFX.CannedMeatloafOpen = VFX.CannedMeatloaf,
                VFX.CannedMinestroneSoupOpen = VFX.CannedMinestroneSoup,
                VFX.CannedMixedBerryPieFillingOpen = VFX.CannedMixedBerryPieFilling,
                VFX.CannedMixedVegetableMedleyOpen = VFX.CannedMixedVegetableMedley,
                VFX.CannedMushroomRavioliOpen = VFX.CannedMushroomRavioli,
                VFX.CannedPassionfruitOpen = VFX.CannedPassionfruit,
                VFX.CannedPeaHamSoupOpen = VFX.CannedPeaHamSoup,
                VFX.CannedPeachPieFillingOpen = VFX.CannedPeachPieFilling,
                VFX.CannedPearSlicesOpen = VFX.CannedPearSlices,
                VFX.CannedPepperSteakStewOpen = VFX.CannedPepperSteakStew,
                VFX.CannedPotatoLeekSoupOpen = VFX.CannedPotatoLeekSoup,
                VFX.CannedPumpkinPureeOpen = VFX.CannedPumpkinPuree,
                VFX.CannedPumpkinSoupOpen = VFX.CannedPumpkinSoup,
                VFX.CannedRaspberryPieFillingOpen = VFX.CannedRaspberryPieFilling,
                VFX.CannedRedBeansAndRiceOpen = VFX.CannedRedBeansAndRice,
                VFX.CannedSalmonOpen = VFX.CannedSalmon,
                VFX.CannedSavoryMinceOpen = VFX.CannedSavoryMince,
                VFX.CannedSlicedMushroomOpen = VFX.CannedSlicedMushroom,
                VFX.CannedSloppyJoeOpen = VFX.CannedSloppyJoe,
                VFX.CannedSpaghettiOpen = VFX.CannedSpaghetti,
                VFX.CannedSpaghettiAndMeatballsOpen = VFX.CannedSpaghettiAndMeatballs,
                VFX.CannedSpinachOpen = VFX.CannedSpinach,
                VFX.CannedSpinachRavioliOpen = VFX.CannedSpinachRavioli,
                VFX.CannedSteakOnionStewOpen = VFX.CannedSteakOnionStew,
                VFX.CannedStrawberryPieFillingOpen = VFX.CannedStrawberryPieFilling,
                VFX.CannedThreeBeanMixOpen = VFX.CannedThreeBeanMix,
                VFX.CannedTomatoSoupOpen = VFX.CannedTomatoSoup,
                VFX.CannedVegetableStewOpen = VFX.CannedVegetableStew,
                VFX.CannedVegetarianChiliOpen = VFX.CannedVegetarianChili,
                VFX.CannedWhiteBeansOpen = VFX.CannedWhiteBeans,
            }]],
		},
	}

	for recipeName, def in pairs(recipeList) do
		local recipe = getScriptManager():getCraftRecipe(recipeName)
		if recipe then
			recipe:getInputs():clear()
			recipe:getOutputs():clear()
			local wrapped = "{ inputs { " .. def.inputs .. " } outputs { " .. def.outputs .. " } " .. def.mapper .. " }"
			recipe:Load(recipeName, wrapped)
		end
	end
end

Events.OnInitWorld.Add(EditJCTDTRecipes)
